export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_VENDORS = "GET_VENDORS";
export const VENDOR_LOADING = "VENDOR_LOADING";
export const VENDOR_DELETING = "VENDOR_DELETING";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_ADDING = "CATEGORY_ADDING";
