export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_VENDORS = 'GET_VENDORS';
export const VENDOR_LOADING = 'VENDOR_LOADING';
export const VENDOR_UPDATING = 'VENDOR_UPDATING';
export const VENDOR_UPDATED = 'VENDOR_UPDATED';
export const VENDOR_DELETING = 'VENDOR_DELETING';
export const VENDOR_ADDING = 'VENDOR_ADDING';
export const VENDOR_TOGGLEBLOCK = 'VENDOR_TOGGLEBLOCK';
export const VENDOR_TYPEAHEAD_UPDATE = 'VENDOR_TYPEAHEAD_UPDATE';

export const CATEGORY_EDITING = 'CATEGORY_EDITING';
export const CATEGORY_EDITED = 'CATEGORY_EDITED';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_UPDATING = 'CATEGORY_UPDATING';
export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';
export const CATEGORY_ADDING = 'CATEGORY_ADDING';
export const CATEGORY_DELETING = 'CATEGORY_DELETING';
export const CATEGORY_TOGGLEBLOCK = 'CATEGORY_TOGGLEBLOCK';
export const CATEGORY_TYPEAHEAD_UPDATE = 'CATEGORY_TYPEAHEAD_UPDATE';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_RANDOM_PRODUCTS = 'GET_RANDOM_PRODUCTS';
export const GET_PRODUCTS_IMAGE_RANDOM = 'GET_PRODUCTS_IMAGE_RANDOM';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_IMAGE = 'GET_PRODUCT_IMAGE';
export const GET_PRODUCT_IMAGE_CUSTOMER = 'GET_PRODUCT_IMAGE_CUSTOMER';
export const PRODUCT_EDITING = 'PRODUCT_EDITING';
export const PRODUCT_EDITED = 'PRODUCT_EDITED';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const PRODUCTS_UPDATING = 'PRODUCTS_UPDATING';
export const PRODUCTS_UPDATED = 'PRODUCTS_UPDATED';
export const PRODUCT_ADDING = 'PRODUCT_ADDING';
export const PRODUCTS_TOGGLEBLOCK = 'PRODUCTS_TOGGLEBLOCK';
export const PRODUCTS_DELETING = 'PRODUCTS_DELETING';
export const GET_A_PRODUCT_VENDOR = 'GET_A_PRODUCT_VENDOR';
export const PRODUCT_INVENTORY_EDITED = 'PRODUCT_INVENTORY_EDITED';
export const GET_VENDOR_INVENTORY = 'GET_VENDOR_INVENTORY';

export const CLEAR_CURRENT_VENDORS = 'CLEAR_CURRENT_VENDORS';
export const CLEAR_CURRENT_PRODUCTS = 'CLEAR_CURRENT_PRODUCTS';
export const CLEAR_CURRENT_CATEGORIES = 'CLEAR_CURRENT_CATEGORIES';

export const GET_PRODUCT_VENDOR = 'GET_PRODUCT_VENDOR';
export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';

export const GET_USERS = 'GET_USERS';
export const USER_LOG_IN = 'USER_LOG_IN';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_UPDATING = 'USER_UPDATING';
export const USER_UPDATED = 'USER_UPDATED';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
